# Tensor Creation

In [9]:
import torch
torch.__version__

torch.cuda.get_device_properties(0)

_CudaDeviceProperties(name='NVIDIA GeForce RTX 3060', major=8, minor=6, total_memory=12287MB, multi_processor_count=28)

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [13]:
MATRIX = torch.tensor([[1,2,1],[3,4,5],[8,7,6]])
MATRIX

tensor([[1, 2, 1],
        [3, 4, 5],
        [8, 7, 6]])

In [14]:
MATRIX.shape


torch.Size([3, 3])

In [15]:
MATRIX.ndim

2

In [38]:
random_tensor = torch.rand(size=(16,16,3))
#also accepts torch.rand(16,16,3)
random_tensor

tensor([[[6.9985e-02, 9.5294e-01, 8.4915e-01],
         [4.7097e-01, 5.3741e-01, 2.3915e-01],
         [5.8441e-01, 3.4211e-01, 1.4069e-01],
         [4.5532e-01, 6.2859e-01, 6.5568e-01],
         [4.3370e-02, 2.5893e-01, 2.2643e-01],
         [1.7586e-01, 9.0596e-01, 7.5049e-01],
         [9.4846e-01, 9.1880e-01, 1.7028e-01],
         [1.2802e-01, 9.9236e-01, 2.2736e-01],
         [2.1284e-01, 3.4104e-01, 7.7065e-02],
         [1.3006e-01, 8.1048e-02, 4.1026e-01],
         [1.8022e-01, 8.5796e-01, 2.5389e-01],
         [8.3916e-01, 7.3028e-01, 3.5081e-01],
         [8.4367e-01, 8.2771e-01, 8.8801e-01],
         [5.5539e-01, 9.0304e-01, 7.6135e-02],
         [8.0584e-01, 8.7643e-01, 8.7284e-01],
         [4.2812e-01, 6.2332e-01, 2.0104e-01]],

        [[4.7122e-01, 8.1257e-01, 4.8348e-01],
         [4.8596e-01, 7.0742e-01, 2.6522e-01],
         [5.0379e-02, 9.8714e-01, 4.8283e-01],
         [8.8338e-01, 5.3761e-01, 9.5516e-01],
         [7.8141e-01, 3.0405e-01, 2.1905e-01],
         [3

In [20]:
zeros = torch.zeros(size=(5,5,3))
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [21]:
ones = torch.ones(size=(5,4,3))
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [29]:
zero_to_ten = torch.arange(start=0,end=9,step=1)
zero_to_ten.shape

torch.Size([9])

In [32]:
#copying dimensions

ones_to_zeroes = torch.zeros_like(ones)
#can also be ones_like
#ones_again = torch.ones_like(ones_to_zeroes)
ones_to_zeroes.shape

torch.Size([5, 4, 3])

# Basic Operations

In [40]:
tensor = torch.rand(3,4,3)
tensor

tensor([[[0.8750, 0.0982, 0.8202],
         [0.9435, 0.2332, 0.8357],
         [0.0889, 0.4712, 0.2037],
         [0.0792, 0.3240, 0.1870]],

        [[0.0027, 0.2877, 0.7758],
         [0.4147, 0.9177, 0.3812],
         [0.8904, 0.3411, 0.8498],
         [0.3163, 0.3998, 0.6006]],

        [[0.0737, 0.8744, 0.9655],
         [0.0539, 0.5428, 0.3144],
         [0.1730, 0.4053, 0.1264],
         [0.3761, 0.4821, 0.2989]]])

In [46]:
# This is element-wise
# This also work for division operations
tensor = tensor * 10
tensor

tensor([[[20.8750, 20.0982, 20.8202],
         [20.9435, 20.2332, 20.8357],
         [20.0889, 20.4712, 20.2037],
         [20.0792, 20.3240, 20.1870]],

        [[20.0027, 20.2877, 20.7758],
         [20.4147, 20.9177, 20.3812],
         [20.8904, 20.3411, 20.8498],
         [20.3163, 20.3998, 20.6006]],

        [[20.0737, 20.8744, 20.9655],
         [20.0539, 20.5428, 20.3144],
         [20.1730, 20.4053, 20.1264],
         [20.3761, 20.4821, 20.2989]]])

In [47]:
# This is also element-wise
# This also works for subtraction
tensor = tensor + 100
tensor

tensor([[[120.8750, 120.0982, 120.8202],
         [120.9435, 120.2332, 120.8357],
         [120.0889, 120.4712, 120.2037],
         [120.0792, 120.3240, 120.1870]],

        [[120.0027, 120.2877, 120.7758],
         [120.4147, 120.9177, 120.3811],
         [120.8904, 120.3411, 120.8498],
         [120.3163, 120.3998, 120.6006]],

        [[120.0737, 120.8744, 120.9655],
         [120.0539, 120.5428, 120.3144],
         [120.1730, 120.4053, 120.1264],
         [120.3761, 120.4821, 120.2989]]])

### Matrix Multiplication
The shapes of the multiplicands must match in the inner layer!
The resulting shape is that of the outer dimensions

In [50]:
tensor1 = torch.rand(3,5)
tensor2 = torch.rand(5,4)

In [53]:
tensor3 = torch.matmul(tensor1, tensor2)
#torch.matmul can be shortened to torch.mm
tensor3

tensor([[1.6419, 1.6047, 2.2177, 1.9540],
        [0.7356, 0.9592, 1.6313, 1.3038],
        [1.3244, 1.3766, 1.6879, 1.4326]])

In [54]:
tensor3.shape

torch.Size([3, 4])