# Tensor Creation

In [1]:
import torch
torch.__version__

# torch.cuda.get_device_properties(0)

'2.5.1+cpu'

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
MATRIX = torch.tensor([[1,2,1],[3,4,5],[8,7,6]])
MATRIX

tensor([[1, 2, 1],
        [3, 4, 5],
        [8, 7, 6]])

In [8]:
MATRIX.shape


torch.Size([3, 3])

In [9]:
MATRIX.ndim

2

In [10]:
random_tensor = torch.rand(size=(16,16,3))
#also accepts torch.rand(16,16,3)
random_tensor

tensor([[[0.0312, 0.6432, 0.1616],
         [0.0335, 0.1719, 0.1072],
         [0.0516, 0.9785, 0.7281],
         [0.5068, 0.5838, 0.8525],
         [0.9630, 0.8201, 0.0909],
         [0.9240, 0.4074, 0.4800],
         [0.1119, 0.7768, 0.7318],
         [0.2150, 0.6910, 0.4523],
         [0.1638, 0.2776, 0.3036],
         [0.7130, 0.2080, 0.8046],
         [0.8341, 0.6315, 0.5838],
         [0.5037, 0.9022, 0.5024],
         [0.3403, 0.9576, 0.6724],
         [0.4008, 0.6913, 0.5924],
         [0.7342, 0.8321, 0.6766],
         [0.4773, 0.8573, 0.9192]],

        [[0.5702, 0.2442, 0.8373],
         [0.0209, 0.0599, 0.1391],
         [0.2534, 0.2877, 0.6399],
         [0.4138, 0.4658, 0.5433],
         [0.9096, 0.1147, 0.8140],
         [0.2772, 0.1652, 0.4800],
         [0.9544, 0.6535, 0.4885],
         [0.4034, 0.4163, 0.4703],
         [0.0961, 0.1865, 0.0743],
         [0.6390, 0.4328, 0.5432],
         [0.9925, 0.2736, 0.8898],
         [0.2431, 0.2609, 0.7752],
         [0.5915, 

In [11]:
zeros = torch.zeros(size=(5,5,3))
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [12]:
ones = torch.ones(size=(5,4,3))
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [13]:
zero_to_ten = torch.arange(start=0,end=9,step=1)
zero_to_ten.shape

torch.Size([9])

In [14]:
#copying dimensions

ones_to_zeroes = torch.zeros_like(ones)
#can also be ones_like
#ones_again = torch.ones_like(ones_to_zeroes)
ones_to_zeroes.shape

torch.Size([5, 4, 3])

# Basic Operations

In [15]:
tensor = torch.rand(3,4,3)
tensor

tensor([[[0.0606, 0.9187, 0.8780],
         [0.6948, 0.8213, 0.4006],
         [0.2072, 0.4610, 0.7654],
         [0.7742, 0.6407, 0.8345]],

        [[0.1483, 0.5870, 0.7222],
         [0.2599, 0.2819, 0.1459],
         [0.1312, 0.0719, 0.5984],
         [0.9923, 0.7768, 0.5817]],

        [[0.7737, 0.1135, 0.5071],
         [0.9182, 0.1184, 0.7009],
         [0.6778, 0.6421, 0.1198],
         [0.3685, 0.6965, 0.6954]]])

In [16]:
# This is element-wise
# This also work for division operations
tensor = tensor * 10
tensor

tensor([[[0.6065, 9.1873, 8.7799],
         [6.9475, 8.2126, 4.0059],
         [2.0720, 4.6098, 7.6540],
         [7.7423, 6.4070, 8.3447]],

        [[1.4828, 5.8704, 7.2223],
         [2.5994, 2.8190, 1.4594],
         [1.3119, 0.7188, 5.9836],
         [9.9225, 7.7681, 5.8167]],

        [[7.7366, 1.1345, 5.0705],
         [9.1822, 1.1835, 7.0090],
         [6.7776, 6.4212, 1.1979],
         [3.6848, 6.9648, 6.9542]]])

In [17]:
# This is also element-wise
# This also works for subtraction
tensor = tensor + 100
tensor

tensor([[[100.6065, 109.1873, 108.7799],
         [106.9475, 108.2126, 104.0059],
         [102.0720, 104.6098, 107.6540],
         [107.7423, 106.4070, 108.3447]],

        [[101.4828, 105.8704, 107.2223],
         [102.5993, 102.8190, 101.4594],
         [101.3119, 100.7188, 105.9836],
         [109.9225, 107.7681, 105.8167]],

        [[107.7366, 101.1345, 105.0705],
         [109.1822, 101.1835, 107.0089],
         [106.7776, 106.4212, 101.1979],
         [103.6848, 106.9648, 106.9542]]])

### Matrix Multiplication
The shapes of the multiplicands must match in the inner layer!
The resulting shape is that of the outer dimensions

In [18]:
tensor1 = torch.rand(3,5)
tensor2 = torch.rand(5,4)

In [19]:
tensor3 = torch.matmul(tensor1, tensor2)
#torch.matmul can be shortened to torch.mm
tensor3

tensor([[1.9012, 1.2870, 1.2629, 1.6047],
        [0.9602, 1.1431, 0.5468, 0.6288],
        [1.4084, 1.2846, 0.8640, 1.1984]])

In [20]:
tensor3.shape

torch.Size([3, 4])